#!/bin/bash

### define variables ###
OUTDIR="${1}"
mkdir -p ${OUTDIR}


### enhancers as positive controls ###
:> ${OUTDIR}/Enhancers.fa

echo ">35S" >> ${OUTDIR}/Enhancers.fa
echo "GGAAAGGCCATCGTTGAAGATGCCTCTGCCGACAGTGGTCCCAAAGATGGACCCCCACCCACGAGGAGCATCGTGGAAAAAGAAGACGTTCCAACCACGTCTTCAAAGCAAGTGGATTGATGTGATATCTCCACTGACGTAAGGGATGACGCACAATCCCACTATCCTTC" >> ${OUTDIR}/Enhancers.fa
echo ">35S(GG)" >> ${OUTDIR}/Enhancers.fa
echo "GGAAAGGCCATCGTTGAAGATGCCTCTGCCGACAGTGGTCCCAAAGGTGGACCCCCACCCACGAGGAGCATCGTGGAAAACGAAGTCGTTCCAACCACGGCTTCAAAGCAAGTGGATGGATGTGATATCTCCACTGACGTAAGGGATGACGCACAATCCCACTATCCTTC" >> ${OUTDIR}/Enhancers.fa
echo ">AB80" >> ${OUTDIR}/Enhancers.fa
echo "ATATATACCTTACACTTCTGAGTTAGAGAAGCAGAGCCCCATAATTAAGCCTATTTTATGAAAAAAATAATATTATGTTGAGTCATATATCCATAAGAATCCCCACAGTCACACATGGAAGAGCAGCATTGGATACAAATGATATGAAGATTTTGATCCATGAACGGATT" >> ${OUTDIR}/Enhancers.fa
echo ">Cab-1" >> ${OUTDIR}/Enhancers.fa
echo "CTACACATTTTAAGCCAGCGGACTCTTTCGACTTGTCTTACAAAAGCTGGTCCAGTCACGAGCCTTAGCCCTAACCATAGCCACAAGTACATCTCATCCATTTAAGGCCTCTGCGTGCACCAATGGCATCCAAGCTGCAGATTTCTTTTCACCACCGTCTCTCTTGTCAG" >> ${OUTDIR}/Enhancers.fa
echo ">rbcS-E9" >> ${OUTDIR}/Enhancers.fa
echo "TACTGTTGTTAGTTTTTTCAGTTAGCTTAGTGGGCATCTTACACGTGGCATTATTATCCTATTGGTGGCTAATGATAAGGTTAGCACACAAAACTTTTCAATCTTGTGTGGTTAATATGACTGCAAAGTTTATCATTTTCACAATCCAACAAACTGGTTCTAGGCAGTGG" >> ${OUTDIR}/Enhancers.fa


### get insulator sequences ###
if [ ! -f "${OUTDIR}/Insulators.fa" ]; then
  curl "https://www.ncbi.nlm.nih.gov/sviewer/viewer.fcgi?id=214003639&db=nuccore&report=fasta&retmode=text" \
    | awk '$0 != ""' \
    > ${OUTDIR}/Insulators.fa
  echo ">sIns1" >> ${OUTDIR}/Insulators.fa
  echo -e "AGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGT\n\
TGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGT\n\
TTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGA\n\
ATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACA\n\
TATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGA\n\
CGTCCAACATATGGCACCGGAGGCTTTCGTCTTCAC" >> ${OUTDIR}/Insulators.fa
  echo ">gypsy" >> ${OUTDIR}/Insulators.fa
  echo -e "CACGTAATAAGTGTGCGTTGAATTTATTCGCAAAAACATTGCATATTTTCGGCAAAGTAAAATTTTGTTG\n\
CATACCTTATCAAAAAATAAGTGCTGCATACTTTTTAGAGAAACCAAATAATTTTTTATTGCATACCCGT\n\
TTTTAATAAAATACATTGCATACCCTCTTTTAATAAAAAATATTGCATACTTTGACGAAACAAATTTTCG\n\
TTGCATACCCAATAAAAGATTATTATATTGCATACCCGTTTTTAATAAAATACATTGCATACCCTCTTTT\n\
AATAAAAAATATTGCATACGTTGACGAAACAAATTTTCGTTGCATACCCAATAAAAGATTATTATATTGC\n\
ATACCTTTTCTTGCCATACCATTTAGCCGATCAATT" >> ${OUTDIR}/Insulators.fa

fi


### tile across the full-length insulators ###
awk '{
    if (substr($1, 1, 1) == ">") {
      if ($0 ~ /TBS/) {name = ">TBS"; step = 84}
      else {name = $1; step = 72}}
    else {sequences[name":"step] = sequences[name":"step] $1}}
    END{for (seq in sequences) {
      split(seq, nast, ":");
      name = nast[1]; step = nast[2]; sequence = sequences[seq]; id = 1
      for (i = 1; i <= length(sequence) - 169; i += step) {
        print name"-"id"\n"substr(sequence, i, 170);
        id += 0.5
      }
    }}' ${OUTDIR}/Insulators.fa \
  > ${OUTDIR}/Insulator_tiles.fa


### combine ###
cat ${OUTDIR}/Enhancers.fa ${OUTDIR}/Insulator_tiles.fa > ${OUTDIR}/Enhancers+Insulators_final.fa